### ISSUE TITLE
Switching to Qbs build system

### ISSUE THREAD

**Issue by bjorn** [flathub/org.mapeditor.Tiled#10]
The "qmake" project files in the Tiled repository have been in maintenance mode for years, and my goal is to eventually get rid of them because maintaining two builds systems (qmake and Qbs) is a pain. How feasible would it be to switch to Qbs for building the Flatpak?

**Comment by syvb** [comment]
I opened [a PR](https://github.com/flathub/org.mapeditor.Tiled/pull/11) to update the build system.

**Comment by bjorn** [comment]
Wow, that was fast @Smittyvb, thanks!

But I think there might now be a debug build being shipped, I've left a comment regarding this on the PR.
