### ISSUE TITLE
Version wrong on flathub.org

### ISSUE THREAD

**Issue by bjorn** [flathub/org.mapeditor.Tiled#15]
The version displayed at https://flathub.org/apps/details/org.mapeditor.Tiled is 2019.07.05, even though it is a build of Tiled 1.8.2, published on February 23, 2022.

@TingPing Do you have an idea what this version is based upon?

**Comment by TingPing** [comment]
It comes from here: https://github.com/mapeditor/tiled/blob/master/org.mapeditor.Tiled.appdata.xml#L17-L24

**Comment by bjorn** [comment]
> It comes from here: [https://github.com/mapeditor/tiled/blob/master/org.mapeditor.Tiled.appdata.xml#L17-L24](https://github.com/mapeditor/tiled/blob/master/org.mapeditor.Tiled.appdata.xml?rgh-link-date=2022-02-23T19%3A09%3A13Z#L17-L24)

Ah, and apparently some caching is going on, since now I see the version displayed at https://flathub.org/apps/details/org.mapeditor.Tiled reflects the latest version listed there, 1.8.0.

Thanks! I'll make sure to update the version in the `appdata.xml` as part of the release process.
