### ISSUE TITLE
Problem with testing the 1.8.4 build

### ISSUE THREAD

**Issue by bjorn** [flathub/org.mapeditor.Tiled#16]
So, I've done the update to Tiled 1.8.4 and now I wanted to test [the resulting build](https://flathub.org/builds/#/builders/32/builds/84337). However, I'm running into the following issue:
```
bjorn@thor:~$ flatpak install https://dl.flathub.org/build-repo/82199/org.mapeditor.Tiled.flatpakref
error: The application org.mapeditor.Tiled/x86_64/stable requires the runtime org.kde.Platform/x86_64/5.15 which was not found
bjorn@thor:~$ flatpak install org.kde.Platform/x86_64/5.15
Looking for matches…
Skipping: org.kde.Platform/x86_64/5.15 is already installed
```
Does anybody with more Flatpak experience have an idea what might be going on here? I'm running Fedora 35 at the moment and I already have the `org.mapeditor.Tiled` Flatpak for 1.8.2 installed (though uninstalling it didn't change a thing).

**Comment by TingPing** [comment]
I'm not certain what is happening, but you could try explicitly using `--user` or `--system`. Maybe that will have an effect.

(I couldn't quickly test it as the test repo was already gone)

**Comment by bjorn** [comment]
@TingPing Thanks, I wasn't aware of this distinction, will try next time!

**Comment by bjorn** [comment]
Alright, I did another build where I have updated the runtime version, and again I ran into this issue:
```
$ flatpak install https://dl.flathub.org/build-repo/89464/org.mapeditor.Tiled.flatpakref 
error: The application org.mapeditor.Tiled/x86_64/stable requires the runtime org.kde.Platform/x86_64/5.15-21.08 which was not found
```
But adding `--user` fixed it:
```
$ flatpak install https://dl.flathub.org/build-repo/89464/org.mapeditor.Tiled.flatpakref --user

org.mapeditor.Tiled permissions:
    ipc     network     wayland     x11     dri    file access [1]    dbus access [2]

    [1] host, xdg-config/kdeglobals:ro
    [2] com.canonical.AppMenu.Registrar, org.kde.kconfig.notify


        ID                           Branch          Op          Remote                Download
 1. [✓] org.mapeditor.Tiled          stable          i           tiled-origin          8.0 MB / 8.2 MB

Installation complete.
```
Fortunately the runtime update seems to work fine. I think the outdated runtime might be what is causing me to not find Tiled at all anymore in Software.
