### ISSUE TITLE
Don't ship Qbs in the package

### ISSUE THREAD

**Issue by bjorn** [flathub/org.mapeditor.Tiled#22]
I noticed that Qbs is actually part of the distributed Flatpak, even along with a bunch of its auto-tests (at least, since the change to cmake in #21):

```
bjorn@thor:~$ flatpak run --command=sh org.mapeditor.Tiled
[📦 org.mapeditor.Tiled ~]$ ls /app/bin
qbs		    qbs-setup-toolchains  tst_blackbox-apple
qbs_benchmarker     terraingenerator	  tst_blackbox-baremetal
qbs-config	    tiled		  tst_blackbox-clangdb
qbs-config-ui	    tmxrasterizer	  tst_blackbox-java
qbs-create-project  tmxviewer		  tst_blackbox-joblimits
qbs_fuzzy-test	    tst_api		  tst_blackbox-qt
qbs-setup-android   tst_blackbox	  tst_blackbox-windows
qbs-setup-qt	    tst_blackbox-android  tst_cmdlineparser
```

This of course needlessly increases the size of the package. Qbs is only a build-time dependency and should be cleaned up somehow.

**Comment by TingPing** [comment]
`"cleanup": ["*"]`

**Comment by bjorn** [comment]
> "cleanup": ["*"]

Thanks, I've tried to include this in #21 (https://github.com/flathub/org.mapeditor.Tiled/pull/21/commits/d79d7c139c3bd1de3fc2870627821460d817f635).
